version: '3'

services:
    web:
        build: ./docker/nginx
        #image: nginx
        ports:
            - "80:80"
        links: 
            - php-fpm
            - mysql
        volumes: 
            - .:/var/www/html/
        depends_on:
            - php-fpm
            - mysql

    php-fpm:
        build: ./docker/php-fpm
        #ports:
            #- "9000:9000"
        expose:
            - 9000
        volumes: 
            - .:/var/www/html/

    mysql:
        build: ./docker/mysql
        #ports: 
            #- "3306:3306"
        expose:
            - 3306
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        restart: always
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
